# Generated by Django 3.0.3 on 2021-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter customer name', max_length=20)),
                ('sector', models.CharField(default=None, help_text='Enter sector', max_length=20)),
                ('industry', models.CharField(default=None, help_text='Enter industry', max_length=20)),
                ('phone', models.CharField(default=None, help_text='Enter phone number', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(help_text='Enter customer gender', max_length=20)),
                ('date_birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
