# Generated by Django 3.0.3 on 2021-02-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(default=None, help_text='Enter account id', max_length=20)),
                ('title', models.CharField(default=None, help_text='Enter account title', max_length=20)),
                ('account_bal', models.CharField(default=None, help_text='Enter account balance', max_length=20)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cust.customer_tab')),
            ],
        ),
    ]
